### PR TITLE
More detailed error message in case of command parse error

### LINKED ISSUE #597: Unknown command: toggle & sort
## Description
`toggle` and `sort` are listed as available commands in [README](https://github.com/hrkfdn/ncspot#commands), but not actually usable.

## Steps to reproduce
1. Play any playlist
2. Type <kbd>:</kbd>, followed by either `toggle` or `sort`
3. UI prompts `ERROR: Unknown command: "toggle/sort"`

## System
 - OS: Manjaro KDE
 - Terminal: Yakuake & Konsole
 - Version: 0.8.2
 - Installed from: AUR & cargo

### PR DESCRIPTION
**Pull request by cyqsimon**
## Change Summary
- A failed command parse now returns more detailed error info, closes #597
- Added API:
  - `pub enum command::CommandParseError`
- Changed API:
  - `pub fn command::parse(&str) -> Option<Vec<Command>>` -> `pub fn command::parse(&str) -> Result<Vec<Command>, CommandParseError>`
- Breaking changes:
  - Some commands previously allow bad args silently and perform some default action. These cases will now fail fast.
    - Examples:
      - `shuffle onn` (misspelled `on`) no longer toggles shuffle.
      - `volup -10` (negative not allowed) no longer increases volume by 1%.
      - `sort title desending` (misspelled `descending`) no longer sorts in ascending.
    - Commands affected: `shuffle`, `repeat`, `save`, `volup`, `voldown`, `sort`
  - Continuous spaces in commands are now interpreted as one
    - Examples:
      - `sort title  descending` (two spaces between `args[0]` and `args[1]`, doesn't show up on rendered markdown) no longer sorts in ascending.
    - Potentially adverse consequences:
      - `newplaylist` can no longer create a playlist containing multiple continuous spaces.

## Feature Preview
feature-preview

### CODE REVIEW

File: src/command.rs [hunk 1]
```diff
@@ -271,226 +305,351 @@ pub fn parse(input: &str) -> Option<Vec<Command>> {
...
+                    Some('-') => i32::try_from(unsigned_millis)
+                        .map(|millis| SeekDirection::Relative(-millis)),
+                    _ => Ok(SeekDirection::Absolute(unsigned_millis)),
+                }
+                .map_err(|_| ArgParseError {
+                    arg: duration_raw,
+                    err: "Duration value too large".into(),
+                })?;
+                Command::Seek(seek_direction)
+            }
```
Comment (cyqsimon) [inline src/command.rs:530]: @hrkfdn I would like to know your opinion on keeping backward compatibility for `seek [+|-]<milliseconds>`.  It caused me a lot of headache trying to write this code cleanly, but I still ended up with this mess.

If you think keeping backward compatibility here is not so important, I'm happy to go ahead and remove it.

File: src/command.rs [hunk 2]
```diff
@@ -271,226 +305,351 @@ pub fn parse(input: &str) -> Option<Vec<Command>> {
...
+            "focus" => {
+                let &target = args.get(0).ok_or(InsufficientArgs {
+                    cmd: command.into(),
+                    hint: Some("queue|search|library".into()),
+                })?;
+                // TODO: this really should be strongly typed
+                Command::Focus(target.into())
```
Comment (cyqsimon) [inline src/command.rs:537]: `Command::Focus` currently accepts a `String`. It is possible to strongly type it with an enum?

File: src/command.rs [hunk 3]
```diff
@@ -271,226 +305,351 @@ pub fn parse(input: &str) -> Option<Vec<Command>> {
...
+            "reload" => Command::ReloadConfig,
             "insert" => {
-                if args.is_empty() {
-                    Some(Command::Insert(None))
-                } else {
-                    args.get(0)
-                        .map(|url| Command::Insert(Some((*url).to_string())))
-                }
+                // IDEA: this should fail fast too
+                Command::Insert(args.get(0).map(|&url| url.into()))
```
Comment (cyqsimon) [inline src/command.rs:575]: Currently if the user inputs a bad URL, the command will run and fail silently without feedback. Ideally I would like to make it fail fast here too, but I know too little about the command executor to make edits confidently.

File: src/command.rs [hunk 4]
```diff
@@ -271,226 +305,351 @@ pub fn parse(input: &str) -> Option<Vec<Command>> {
...
-            "noop" => Some(Command::Noop),
-            "redraw" => Some(Command::Redraw),
-            "exec" => Some(Command::Execute(args.join(" "))),
-            _ => None,
+            "noop" => Command::Noop,
+            "redraw" => Command::Redraw,
+            "exec" => Command::Execute(args.join(" ")),
+            _ => Err(NoSuchCommand {
+                cmd: command.into(),
+            })?, // I'm surprised this compiles lol
```
Comment (cyqsimon) [inline src/command.rs:650]: I didn't think this would compile. Happy surprise.

File: src/main.rs [hunk 5]
```diff
@@ -292,17 +292,19 @@ async fn main() -> Result<(), String> {
...
                     }
-                } else {
-                    let mut main = s.find_name::<ui::layout::Layout>("main").unwrap();
-                    let err_msg = format!("Failed to parse command(s): \"{}\"", cmd_without_prefix);
-                    main.set_result(Err(err_msg));
+                    Err(err) => {
+                        let mut main = s.find_name::<ui::layout::Layout>("main").unwrap();
+                        let err_msg = format!("Failed to parse command(s): {}", err);
+                        main.set_result(Err(err_msg));
+                    }
```
Comment (cyqsimon) [inline src/main.rs:307]: This has the occasional problem where the error message's length exceeds the width of the terminal window, causing part of the message to be missing. Is there anything we can do about this?

**Comment by cyqsimon** [comment]
Also I just took a look at my old issue and realised that this PR doesn't *really* close it in its current state. Commands like `sort`, if ran in an unsupported view, will still fail silently. This will require changes to the command executor.

File: src/main.rs (hunk 5 above)
Comment (cyqsimon) [reply src/main.rs]: I got rid of some wordiness, but the problem is not solved at the root. I'm thinking of some kind of auto-scroll or multi-line message.

File: src/command.rs [hunk 6]
```diff
@@ -271,226 +305,351 @@ pub fn parse(input: &str) -> Option<Vec<Command>> {
 
     let mut commands = vec![];
     for command_input in command_inputs {
-        let components: Vec<_> = command_input.trim().split(' ').collect();
+        lazy_static! {
+            // https://docs.rs/regex/latest/regex/#example-avoid-compiling-the-same-regex-in-a-loop
+            static ref CONTINUOUS_SPACE_MATCHER: Regex = Regex::new(r" +").unwrap();
+        }
+        let command_sanitised = CONTINUOUS_SPACE_MATCHER.replace_all(&command_input, " ");
+        let components: Vec<_> = command_sanitised.trim().split(' ').collect();
```
Comment (hrkfdn) [inline src/command.rs:313]: Maybe `str.split_whitespace()` is a simpler alternative we can use?

https://doc.rust-lang.org/std/primitive.str.html#method.split_whitespace

File: src/command.rs (hunk 1 above)
Comment (hrkfdn) [reply src/command.rs:530]: Hmm, I don't think it's so bad :smile: 

Ideally we should set the default unit to `ms` or fail when values without units are supplied, otherwise existing custom bindings will confuse users a lot, as they may suddenly seek forward by a couple of hundred seconds. So maybe we should keep it backward compatible for now? WDYT?

File: src/command.rs (hunk 2 above)
Comment (hrkfdn) [reply src/command.rs:537]: I have no preference here, both are fine to me. I think the gain is rather low compared to the effort, as `Layout` already checks if the screen exists when processing the command, but feel free to type it if you prefer.

File: src/command.rs (hunk 3 above)
Comment (hrkfdn) [reply src/command.rs:575]: Ideally yes, we could at least validate the URL or check if it can be parsed using `SpotifyUrl::from_url`. Everything after that requires API calls.

**Review by hrkfdn — COMMENTED** [review]
Thanks for tackling this. I have added some comments.

File: src/command.rs (hunk 1 above)
Comment (cyqsimon) [reply src/command.rs:530]: The reason I suggested to make `second` the default unit is actually quite simple... `parse_duration` crate doesn`t provide any options to configure its default unit, which means we either have to use its default (second), or do the dance we've got here to try parsing to `ms` first.

If you think the code isn't too terrible I'm happy to keep it as is.

File: src/command.rs (hunk 6 above)
Comment (cyqsimon) [reply src/command.rs:313]: Oh bollocks. I knew about this function for some time now, but never understood its point nor have read its documentation. It is better indeed. Thanks for showing me the way.

File: src/command.rs (hunk 2 above)
Comment (cyqsimon) [reply src/command.rs:540]: You're right. It's probably more effort than it's worth unless we're actually considering adding another screen. This can wait for when (and if) that situation arises.

File: src/main.rs (hunk 5 above)
Comment (cyqsimon) [reply src/main.rs]: I took another look today after simply shortening the message and, eh, it's good enough. Too much work than it's worth for now.

**Comment by cyqsimon** [comment]
Okay. I'm pretty happy with the state this PR is in. Problems in #597 are more or less sufficiently addressed right now.

I've also done a bit of code cleanup (e.g. sorting match branches), so hopefully this will make the codebase slightly easier to maintain.

**Comment by hrkfdn** [comment]
Thanks again, looks very good to me. Let's get this in!
