### PR TITLE
fix(mpris): missing `PropertyChanged` signal for volume

### LINKED ISSUE #1328: Changing volume internally does not change MPRIS volume
## Describe the bug
When I change the volume inside the ncspot application, whether by commands, scroll wheel, or keybinds, this does not update MPRIS' idea of ncspot's internal volume. As a matter of fact, the exact same one-sided communication happens with repeat and shuffle. For example...

## To Reproduce
1. Have a song playing so you can tell what's going on.
1. Use MPRIS (I use the Media Player Plasmoid from KDE Plasma) to set ncspot's volume to 100%.
2. Inside ncspot, set the volume (using any method you like) to 50%. The music gets quieter.
3. Use MPRIS to decrement the volume by 5%. It sets ncspot's volume to 95%.

## Expected behavior
In the above example, I expected ncspot's volume to be set to 45% after the final step.

## System
 - OS: Arch Linux
 - Terminal: Konsole
 - Version: 0.13.2-3
 - Installed from: Arch official repositories

## Screenshots

*Changed from inside ncspot, they don't match*

## Debug log
This log was massive, so for clarity I only included the part of the log that actually, y'know, relate to this bug report. I didn't exclude anything from where the log starts to where it ends, however; I only trimmed out the start and end.
[ncspot-debug-1.log](https://github.com/hrkfdn/ncspot/files/13241028/ncspot-debug-1.log)

### Status is passed on during startup
It seems that whenever you start ncspot, the state is loaded into MPRIS. For example, if I set repeat=R1, shuffle=on, volume=70% inside ncspot, MPRIS will have no idea. But if I quit ncspot then restart it, MPRIS is suddenly aware of all those things.
### `playerctl` works, so it might be partially KDE's fault...
I conducted some testing with `playerctl`, and it seems to me like half the fault here is with KDE. 
If I repeat the above methodology but replace the last step with running `playerctl volume -0.05`, *everything works fine*. 
Same goes for `playerctl shuffle toggle`.
`playerctl` doesn't have an absolute command for repeating, so I can't compare there.
My hypothesis, therefore, is that their Plasmoid does not pass on relative commands but appears to store an internal value for volume/repeat/shuffle and then use absolute commands like `playerctl volume 0.95`. Or `playerctl shuffle off` instead of `playerctl shuffle toggle`, depending on the internally stored value.
### ...but not completely
When I use the official Spotify client to do the same tests, I don't get this issue. When I change shuffle, repeat, or volume in Spotify, *the status in the Plasmoid changes to match*. So even if the Plasmoid does keep track of the volume/repeat/shuffle internally, it updates them when Spotify changes something.  Look, I even took a screenshot:

### PR DESCRIPTION
**Pull request by ThomasFrans**
When the volume is changed from inside `ncspot`, also send a `PropertyChanged` signal.

## Describe your changes

- Send a DBus `PropertyChanged` signal every time the volume is changed inside `Spotify`
- Make the `update()` command on the `MprisManager` more general with different signals

## Issue ticket number and link

closes #1328

## Checklist before requesting a review
- [x] Documentation was updated (i.e. due to changes in keybindings, commands, etc.)
- [x] Changelog was updated with relevant user-facing changes (eg. not dependency updates,
  not performance improvements, etc.)

### CODE REVIEW

**Comment by ThomasFrans** [comment]
Two little gotchas with this PR:

1. The signal is sent twice when changing volume over MPRIS. I didn't think it was worth it to duplicate the logic in `Spotify::set_volume()` to solve this as that will probably cause more trouble than it will solve in the long run. I don't see a problem with sending it twice, and there isn't a way to disable it from what I can tell. It this needs to be solved, let me know :)
2. The implementation is a bit 'un-rustlike' because `Spotify` depends on `MprisManager` now and `MprisManager` on `Spotify`, so the `mpris` value in `Spotify` is optional for this reason, to set it afterwards. I don't know of a better way to do this for now.

File: src/mpris.rs [hunk 1]
```diff
@@ -462,8 +463,19 @@ impl MprisPlayer {
     }
 }
 
+/// Commands to control the [MprisManager] worker thread.
+pub enum MprisCommand {
+    /// Notify about playback status and metadata updates.
+    PlaybackUpdated,
+    /// Notify about volume updates.
+    VolumeUpdated,
```
Comment (hrkfdn) [inline src/mpris.rs:471]: Nit: These read more like event names than commands, WDYT?

Comment (ThomasFrans) [reply src/mpris.rs:471]: I completely agree. I should have worked a bit more on this PR before creating it as I don't feel 100% happy with it to be honest. It feels rushed. I'm going to turn it into a draft and have another look at it after the 25th (unless you want to fix the issue earlier of course). I'm currently a bit busy with my studies 🫤

Comment (hrkfdn) [reply src/mpris.rs:471]: No worries, as always, appreciate your contributions and take your time. Good luck with your studies!

**Comment by ThomasFrans** [comment]
I changed the names of the commands and prevented the duplicate message when updating the volume through the MPRIS interface. I will work on the events vs state in another PR to not make this one too big. Before touching the configuration stuff I would _really_ like to add tests to that module because I'm scared to break people's configs if I start changing related types.

Let me know if this PR is ok or you want to solve it in a different way :slightly_smiling_face:

**Review by hrkfdn — APPROVED** [review]
Thank you, LGTM. I was wondering if there's a way to reduce some of the `#[cfg]` conditionals, but I don't see how. Let's get it in! :)

**Comment by ThomasFrans** [comment]
> I was wondering if there's a way to reduce some of the `#[cfg]` conditionals, but I don't see how. Let's get it in! :)

You don't want to know how much I've thought about this as well. It's hard to get right because there are too many combinations and also because any code that isn't used causes clippy warnings which in turn cause CI to fail. The only solution I can see is to use libraries which makes the conditional stuff "someone else's problem" 😄
