### PR TITLE
Fixes a pagination bug that caused items to not load when scrolling with the mouse

### LINKED ISSUE #938: Scroll to load extra items no longer works with the mouse
**Describe the bug**
When there are a lot of items in a listview, there is a text message that says to scroll to get more items loaded. It doesn't work anymore in the most recent version. I think the #918 fix caused this as a side effect.

**To Reproduce**
1. Go to a long podcast (I used "De Universiteit van Vlaanderen Podcast", there's probably normal podcasts as well but this is just the one that triggered the bug for me :smile: )
2. Scroll to the bottom with the mouse

**Expected behavior**
The extra items load at the bottom.

**Screenshots**
image

**System (please complete the following information):**
 - OS: Arch Linux
 - Terminal: Alacritty
 - Version: Latest git version
 - Installed from: AUR

### PR DESCRIPTION
**Pull request by ThomasFrans**
This PR fixes the pagination but that prevented loading. I also added some documentation to some of the less obvious methods. There is still a bug present that causes the pagination message to appear at the bottom of the Browse tab, even when there isn't any more items. Help would be wanted with fixing that. I could also open another separate bug report for that if that's easier :slightly_smiling_face: .

fixes #938

### CODE REVIEW

File: src/ui/listview.rs [hunk 1]
```diff
@@ -72,7 +72,9 @@ impl<I: ListItem> ListView<I> {
             library,
             pagination: Pagination::default(),
             title: "".to_string(),
-        }
+        };
+        result.try_paginate();
```
Comment (hrkfdn) [inline src/ui/listview.rs:76]: Hmm, could you explain why this change is necessary?

File: src/ui/listview.rs [hunk 2]
```diff
@@ -99,10 +101,30 @@ impl<I: ListItem> ListView<I> {
...
+    #[inline]
+    fn try_paginate(&self) {
+        // Paginate if there are more items
+        //  AND
+        //   The selected item is the current last item (keyboard scrolling)
+        //    OR
+        //   The scroller can't scroll further down (mouse scrolling)
+        if self.can_paginate()
+            && (self.selected == self.content.read().unwrap().len().saturating_sub(1)
+                || !self.scroller.can_scroll_down())
```
Comment (hrkfdn) [inline src/ui/listview.rs:122]: I think this will also trigger pagination if you use the keyboard to go down one line and the screen size is large enough to show all items, meaning it can't scroll down any further:
 
[Screencast from 09-15-2022 10:51:52 PM.webm](https://user-images.githubusercontent.com/19884/190506676-5d75597f-9a66-4877-91db-57583984fcbc.webm)

I can't think of a quick fix though, other than passing whether it was a mouse or keyboard move and preventing pagination in case it was a keyboard move, i.e. `!can_scroll_down() && mouse_event`.

But to be honest the inconvenience of handling this is worth it as it's almost not a problem, unless you have a nicer idea.

**Review by hrkfdn — COMMENTED** [review]
Hey, thanks a lot for the PR and the added documentation :)

Some comments below.

> There is still a bug present that causes the pagination message to appear at the bottom of the Browse tab, even when there isn't any more items. Help would be wanted with fixing that. 

Unfortunately I haven't found an entry in "Browse" where I can reproduce this. Do you reckon it's because of the change in this PR or a different issue?

File: src/ui/listview.rs (hunk 1 above)
Comment (ThomasFrans) [reply src/ui/listview.rs:76]: When the page loads on an ultrawide screen for example, it may not show enough items initially to fill the screen. This makes sure that doesn't happen. Maybe there's a better way to solve this...

File: src/ui/listview.rs (hunk 2 above)
Comment (ThomasFrans) [reply src/ui/listview.rs:122]: Oh I thought it was supposed to load more items when that happened. Unless you mean the case where there are no more items to load, which is handled by the `can_paginate` method I think.

**Comment by ThomasFrans** [comment]
Here is a picture of the Browse category problem (blue text at the bottom of the list shouldn't be there, or should expand, but I think there are no more items to display). Something I noticed is there are exactly 50 items, but when debugging, the paginator says there are 51 items, which may cause the problem I think. I know there are some parts of the Spotify API that can only request 50 items at a time, so this may not be a coincidence that it happens with exactly 50 items. I saw there was a way to tell the pagination to add itself as an extra item, which could cause it to draw the text at the bottom, even when there aren't any more items to display.

image

File: src/ui/listview.rs (hunk 2 above)
Comment (hrkfdn) [reply src/ui/listview.rs:122]: It's not really a bug, just a change in behavior. But I think it's fine.

**Comment by hrkfdn** [comment]
> Here is a picture of the Browse category problem in the latest release, so not this branch (blue text at the bottom of the list shouldn't be there, or should expand, but I think there are no more items to display). Something I noticed is there are exactly 50 items, but when debugging, the paginator says there are 51 items, which may cause the problem I think. I know there are some parts of the Spotify API that can only request 50 items at a time, so this may not be a coincidence that it happens with exactly 50 items. I saw there was a way to tell the pagination to add itself as an extra item, which could cause it to draw the text at the bottom, even when there aren't any more items to display.

Sometimes Spotify sends a larger page count than can be fetched :( See also https://github.com/hrkfdn/ncspot/issues/131

Unfortunately I can't reproduce it with my "Browse" list

**Comment by hrkfdn** [comment]
Let's get it in!

**Comment by hrkfdn** [comment]
> Unfortunately I can't reproduce it with my "Browse" list

Whoops, I found the culprit. Fixed in 2be1264, thanks for reporting.

**Comment by ThomasFrans** [comment]
Can confirm that Browse works properly now.
